// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQRS',
    appId: '1:451261949462:android:abc123def456ghi789jkl',
    messagingSenderId: '451261949462',
    projectId: 'universe-fireabse',
    storageBucket: 'universe-fireabse.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummy1234567890ABCDEFGHIJKLMNOPQRS',
    appId: '1:451261949462:ios:abc123def456ghi789jkl',
    messagingSenderId: '451261949462',
    projectId: 'universe-fireabse',
    storageBucket: 'universe-fireabse.appspot.com',
    iosBundleId: 'com.example.universeApp',
  );
}
